### PR TITLE
Update item-ammo-requirements.json

### PR DESCRIPTION
**Pull request by jburleigh1**
First working version. Maybe missing some, will continue to iterate over the next few days if any issues arise.

### CODE REVIEW

**Comment by osrsbox** [comment]
Hey @jburleigh1 - I have compared this data with all items that are in the `ammo` slot. As you know, there are some `ammo` slot items that are not actually range ammo. These are listed below:

```
20220  Holy blessing
20223  Unholy blessing
20226  Peaceful blessing
20229  Honourable blessing
20232  War blessing
20235  Ancient blessing
22941  Rada's blessing 1
22943  Rada's blessing 2
22945  Rada's blessing 3
22947  Rada's blessing 4
```

After removing these, there are 190 items that are equipable in the `ammo` slot. Had a manual look over all of these, and they look pretty accurate to me. In the data below, I have included the item ID, the item name, and the data pulled directly from your new JSON file. Hopefully, this provides some info about which items are missing data.

```
78, Ice arrows, {'ammo_type': 'arrows', 'ammo_tier': 7}
598, Bronze fire arrows, None
825, Bronze javelin, None
826, Iron javelin, None
827, Steel javelin, None
828, Mithril javelin, None
829, Adamant javelin, None
830, Rune javelin, None
831, Bronze javelin(p), None
832, Iron javelin(p), None
833, Steel javelin(p), None
834, Mithril javelin(p), None
835, Adamant javelin(p), None
836, Rune javelin(p), None
877, Bronze bolts, {'ammo_type': 'bolts', 'ammo_tier': 2}
878, Bronze bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 2}
879, Opal bolts, {'ammo_type': 'bolts', 'ammo_tier': 2}
880, Pearl bolts, {'ammo_type': 'bolts', 'ammo_tier': 3}
881, Barbed bolts, {'ammo_type': 'bolts', 'ammo_tier': 2}
882, Bronze arrow, {'ammo_type': 'arrows', 'ammo_tier': 3}
883, Bronze arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 3}
884, Iron arrow, {'ammo_type': 'arrows', 'ammo_tier': 3}
885, Iron arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 3}
886, Steel arrow, {'ammo_type': 'arrows', 'ammo_tier': 4}
887, Steel arrow(p), None
888, Mithril arrow, {'ammo_type': 'arrows', 'ammo_tier': 5}
889, Mithril arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 5}
890, Adamant arrow, {'ammo_type': 'arrows', 'ammo_tier': 6}
891, Adamant arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 6}
892, Rune arrow, {'ammo_type': 'arrows', 'ammo_tier': 7}
893, Rune arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 7}
942, Bronze fire arrows, None
2532, Iron fire arrows, None
2533, Iron fire arrows, None
2534, Steel fire arrows, None
2535, Steel fire arrows, None
2536, Mithril fire arrows, None
2537, Mithril fire arrows, None
2538, Adamant fire arrows, None
2539, Adamant fire arrows, None
2540, Rune fire arrows, None
2541, Rune fire arrows, None
2866, Ogre arrow, {'ammo_type': 'ogre'}
4160, Broad arrows, {'ammo_type': 'arrows', 'ammo_tier': 8}
4740, Bolt rack, {'ammo_type': 'bolt racks'}
4773, Bronze brutal, None
4778, Iron brutal, None
4783, Steel brutal, None
4788, Black brutal, None
4793, Mithril brutal, None
4798, Adamant brutal, None
4803, Rune brutal, {'ammo_type': 'brutals'}
5616, Bronze arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 3}
5617, Iron arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 3}
5618, Steel arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 4}
5619, Mithril arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 5}
5620, Adamant arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 8}
5621, Rune arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 7}
5622, Bronze arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 3}
5623, Iron arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 3}
5624, Steel arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 4}
5625, Mithril arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 5}
5626, Adamant arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 8}
5627, Rune arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 7}
5642, Bronze javelin(p+), None
5643, Iron javelin(p+), None
5644, Steel javelin(p+), None
5645, Mithril javelin(p+), None
5646, Adamant javelin(p+), None
5647, Rune javelin(p+), None
5648, Bronze javelin(p++), None
5649, Iron javelin(p++), None
5650, Steel javelin(p++), None
5651, Mithril javelin(p++), None
5652, Adamant javelin(p++), None
5653, Rune javelin(p++), None
6061, Bronze bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 2}
6062, Bronze bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 2}
8882, Bone bolts, {'ammo_type': 'bone'}
9139, Blurite bolts, {'ammo_type': 'bolts', 'ammo_tier': 3}
9140, Iron bolts, {'ammo_type': 'bolts', 'ammo_tier': 4}
9141, Steel bolts, {'ammo_type': 'bolts', 'ammo_tier': 5}
9142, Mithril bolts, {'ammo_type': 'bolts', 'ammo_tier': 6}
9143, Adamant bolts, {'ammo_type': 'bolts', 'ammo_tier': 7}
9144, Runite bolts, {'ammo_type': 'bolts', 'ammo_tier': 8}
9145, Silver bolts, {'ammo_type': 'bolts', 'ammo_tier': 4}
9236, Opal bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 2}
9237, Jade bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 2}
9238, Pearl bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 3}
9239, Topaz bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 4}
9240, Sapphire bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 5}
9241, Emerald bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 6}
9242, Ruby bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 7}
9243, Diamond bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 7}
9244, Dragonstone bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 8}
9245, Onyx bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 8}
9286, Blurite bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 3}
9287, Iron bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 4}
9288, Steel bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 5}
9289, Mithril bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 6}
9290, Adamant bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 7}
9291, Runite bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 8}
9292, Silver bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 4}
9293, Blurite bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 3}
9294, Iron bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 4}
9295, Steel bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 5}
9296, Mithril bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 6}
9297, Adamant bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 7}
9298, Runite bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 8}
9299, Silver bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 4}
9300, Blurite bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 3}
9301, Iron bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 4}
9302, Steel bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 5}
9303, Mithril bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 6}
9304, Adamant bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 7}
9305, Runite bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 8}
9306, Silver bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 4}
9335, Jade bolts, {'ammo_type': 'bolts', 'ammo_tier': 3}
9336, Topaz bolts, {'ammo_type': 'bolts', 'ammo_tier': 4}
9337, Sapphire bolts, {'ammo_type': 'bolts', 'ammo_tier': 5}
9338, Emerald bolts, {'ammo_type': 'bolts', 'ammo_tier': 6}
9339, Ruby bolts, {'ammo_type': 'bolts', 'ammo_tier': 7}
9340, Diamond bolts, {'ammo_type': 'bolts', 'ammo_tier': 7}
9341, Dragonstone bolts, {'ammo_type': 'bolts', 'ammo_tier': 8}
9342, Onyx bolts, {'ammo_type': 'bolts', 'ammo_tier': 8}
9419, Mith grapple, None
9706, Training arrows, {'ammo_type': 'arrows', 'ammo_tier': 0}
10142, Guam tar, None
10143, Marrentill tar, None
10144, Tarromin tar, None
10145, Harralander tar, None
10158, Kebbit bolts, {'ammo_type': 'kebbits'}
10159, Long kebbit bolts, {'ammo_type': 'kebbits'}
11212, Dragon arrow, {'ammo_type': 'arrows', 'ammo_tier': 9}
11217, Dragon fire arrows, {'ammo_type': 'arrows', 'ammo_tier': 9}
11222, Dragon fire arrows, {'ammo_type': 'arrows', 'ammo_tier': 9}
11227, Dragon arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 9}
11228, Dragon arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 9}
11229, Dragon arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 9}
11700, Bronze arrow, None
11701, Iron arrow, None
11702, Steel arrow, None
11703, Mithril arrow, None
11875, Broad bolts, {'ammo_type': 'bolts', 'ammo_tier': 8}
19484, Dragon javelin, None
19486, Dragon javelin(p), None
19488, Dragon javelin(p+), None
19490, Dragon javelin(p++), None
20388, Adamant arrow, None
20389, Dragon arrow, None
20600, Rune arrow, None
21316, Amethyst broad bolts, {'ammo_type': 'bolts', 'ammo_tier': 8}
21318, Amethyst javelin, None
21320, Amethyst javelin(p), None
21322, Amethyst javelin(p+), None
21324, Amethyst javelin(p++), None
21326, Amethyst arrow, {'ammo_type': 'arrows', 'ammo_tier': 8}
21328, Amethyst fire arrows, None
21330, Amethyst fire arrows, None
21332, Amethyst arrow(p), {'ammo_type': 'arrows', 'ammo_tier': 8}
21334, Amethyst arrow(p+), {'ammo_type': 'arrows', 'ammo_tier': 8}
21336, Amethyst arrow(p++), {'ammo_type': 'arrows', 'ammo_tier': 8}
21905, Dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21924, Dragon bolts (p), {'ammo_type': 'bolts', 'ammo_tier': 9}
21926, Dragon bolts (p+), {'ammo_type': 'bolts', 'ammo_tier': 9}
21928, Dragon bolts (p++), {'ammo_type': 'bolts', 'ammo_tier': 9}
21932, Opal dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21934, Jade dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21936, Pearl dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21938, Topaz dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21940, Sapphire dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21942, Emerald dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21944, Ruby dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21946, Diamond dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21948, Dragonstone dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21950, Onyx dragon bolts (e), {'ammo_type': 'bolts', 'ammo_tier': 9}
21955, Opal dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21957, Jade dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21959, Pearl dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21961, Topaz dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21963, Sapphire dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21965, Emerald dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21967, Ruby dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21969, Diamond dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21971, Dragonstone dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
21973, Onyx dragon bolts, {'ammo_type': 'bolts', 'ammo_tier': 9}
22227, Bullet arrow, None
22228, Field arrow, None
22229, Blunt arrow, None
22230, Barbed arrow, None
```

**Comment by osrsbox** [comment]
Also, there was a release by the wiki yesterday which provided accurate weapon types: https://oldschool.runescape.wiki/w/Weapon/Types. This data is provided by JaGeX. I think the plan is to implement the following for all weapons into the database:

- `classification` or `weapon_type`: axe, bow etc.
- `combat style`: chop, block, accurate, longrange etc.
- `attack type`: slash, crush
- `attack style`: accurate, aggessive etc.
- `experience`: strength, defence, ranged etc.

As you can see, this will include the `weapon_type` additions you have made. Hopefully this will help everyone, and I think the plan is to incorporate this data into the actual item database. I think your ammo classification scheme could also be included. It seems like it should be included.

Also, thanks heaps for the work on this. I think these new modifications could be a very good addition to the project and very useful.

**Comment by jburleigh1** [comment]
Incredibly helpful to see the data in the way you've laid out above, thanks :) I was cross-referencing the item-summary.json file with this ammo file to get the IDs right :)

I'll work on filling each and every ammo item above.  Not too many to go.

**Comment by jburleigh1** [comment]
Dropping this here for my own reference, and then maybe we can put it somewhere alongside the docs for anyone looking to make use of this.

Proposed tier levels for **bolts**:

|  Ammo Tier | Bolts        |
|--------------|------------|
|          1         | **none** |
|          2         | Bronze    | 
|          3         | Blurite     | 
|          4         | Iron, Silver |
|          5         | Steel        |
|          6         | Mithril|    |
|          7         | Adamant |  
|          8         | Rune, Broad, Amethyst |
|          9         | Dragon   | 

Proposed tier levels for **arrows**:

|  Ammo Tier | Arrows    |
|--------------|------------|
|          1         | Training   |
|          2         | **none** | 
|          3         | Iron, Bronze, Barbed| 
|          4         | Steel |
|          5         | Mithril |
|          6         | Adamant    |
|          7         | Rune, Ice |  
|          8         | Amethyst, Broad |
|          9         | Dragon   | 

Exceptions to the above that have their own weapon / ammo combinations:

|  Exceptions |    |
|--------------|------------|
| Bone Crossbow         | Bone Bolts|
| Hunters Crossbow         | Kebbit, Long Kebbit | 
| Karil's Crossbow         | Bolt Racks | 
| Ogre Bow | Ogre Arrows|
| Comp Ogre Bow | Ogre Arrows, Brutal Arrows |
| Crystal Bow | **none** |
| Craw's Bow | **none** |

**Comment by osrsbox** [comment]
@jburleigh1 - Thanks for finishing the arrow/bolt part of this. To be complete, I think we should also add the classification scheme for Javelins. There are a bunch of JSON validation errors, but I will fix these up. Also, I will _trim_ the item ID list to only include `ammo` slot items (instead of the full list I generated for you). I will also add a readme file to accompany the data, based on your nice tables! Accepting the PR, but will update the mentioned issues.

**Comment by jburleigh1** [comment]
Hey :)

I actually had it in my head that javelins were equipable in the weapon slot and not the ammo slot, but I just looked into it and it looks like that was changed ages ago for the Balista update lol. 

I'll handle the javelin data, gimme a couple of days and I'll put in another pr.

Would it be possible to keep all weapon items in the json list alongside the ammo items? The reason is, in my code I'm looping through all items. When it gets to a ranged item, it goes and checks this file for the weapon type, and then matches that up to the ammo type in this same file. 

Jamie

**Comment by jburleigh1** [comment]
JSON Data has been updated with Javelin info, table below: 

Ammo Tier | Javelins
-- | --
1 | **none**
2 | Bronze
3 | Iron
4 | Steel
5 | Mithril
6 | Adamant
7 | Rune
8 | Amethyst
9 | Dragon

**Pull request merged**
