### PR TITLE
Add weapon definition

### PR DESCRIPTION
**Pull request by osrsbox**
@nwalsh1995 - I have put together a PR for #92. I have been working on the comments you suggested, but am struggling with an elegant solution for: 1) Adding Enum for the combat styles/attack types etc.; and 2) Adding inheritance to the `ItemWeapon` and `ItemEquipment` classes. 

1) The `Enum` solution seems nice, but not sure if I should proceed with adding them. The main issue I have is that there is are so many types. For example, there are 32 combat styles (listed at the bottom of this comment). Is making an Enum for this best practice or problematic? 

2) The inheritance solution is something I want to use, but I am having problems implementing. I have tried a variety of solutions, but having issues loading the item dictionary (JSON file) into the `ItemWeapon` class when using inheritance. I have some hacky solutions, but have not included in the PR. I think I need a push in the right direction for this. We can also add in this functionality at a later date if we want to accept the current PR and open another issue for fixing this in the future.

3) I have removed the `Optional` attributes from the `ItemWeapon` class, and JSON schema. Like you mentioned, I had this for testing only. 

Currently this passes the build and tests. Commit c36f6e56151d467a1add66d6bb91f74946ec86f5 has the code changes to the API and schema. Commit 4009d2fb07e20104ce59e1546b1256d89da5a6da has the changes to the actual `items-json` files and `items-complete.json` to see the actual data.

Listed below are the 32 options for the `combat_style` attributes in `stances`:

```
spell
block
flick
lash
stab
flamer
jab
long fuse
deflect
longrange
spike
chop
flare
explosive
pound
lunge
scorch
pummel
medium fuse
blaze
focus
punch
bash
fend
hack
kick
swipe
smash
reap
slash
accurate
rapid
impale
aim and fire
short fuse
spell (defensive)
```

### CODE REVIEW

**Comment by nwalsh1995** [comment]
@osrsbox hmm, those weren't the types I was thinking of turning into an enum. Isn't it only like slash/stab/crush/defensive etc? A lot of those don't factor into DPS calculations and seem more like flavor. If there are that many, it might be better to just stick them into strings since it would appear that Jagex add new types frequently compared to the normal stab/slash/crush/etc.

**Comment by nwalsh1995** [comment]
Ah now I see where you got them, from the Combat Styles here: https://oldschool.runescape.wiki/w/Weapon/Types

Yes for that many it will be good to do strings. (Also if you didnt want to type 32 things you can write the python code to generate the python code to make the enum xD)

**Comment by nwalsh1995** [comment]
Re: the inheritance problem, if you want to push the code as-is, I will send a PR with the inheritance solution that you can take a look at.

Else, if you would like to include it yourself, you can share the problems you were having getting it to work and potentially we could hop on a call where you can share your screen with me for a bit faster response.

**Comment by osrsbox** [comment]
Thanks @nwalsh1995 for the quick reply. I am traveling at the moment - so can't chat easily. I think the best thing would be to merge the PR as-is - but I will not push a new PyPi package version at the moment. Then feel free to make any changes to the `WeaponDefinition`, `EquipmentDefinition` and/or `ItemDefinition` classes - or anything else that may need modification. 

Thanks for the help. I think my OO weakness is showing in trying to find an elegant/best practice solution. It would be great to see how you code it.

**Pull request merged**
