### PR TITLE
move code to package it for installation

### PR DESCRIPTION
**Pull request by nwalsh1995**
This is to attempt to start the packaging for #17

Some things we want to be aware of:

1. The subdirectories in the `docs/` folder will not be included with install. I was worried this would make the installation too big but not sure what it breaks.
2. I haven't tested all the command line scripts. Potentially we want to merge and fix as we go since we aren't supporting users at this point.
3. There are fields on the setup.py that I added TODO statements for. @osrsbox should decide on which values to use for those fields.

```
$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osrsbox_db.item_api_tools.AllItems import AllItems
>>>
```

### CODE REVIEW

**Comment by osrsbox** [comment]
Hey @nwalsh1995 - very nice progress! I can easily add the missing parts to the `setup.py` file. However, the current merge request will break one major function of the project. The `docs` folder in the root directory is key to providing publicly available data. I use the functionality of GitHub Pages to host the JSON files in the public `docs` folder which is also linked to the osrsbox.com URL. Basically, anyone can do the following:

```
https://www.osrsbox.com/osrsbox-db/<any-file-in-the-docs-folder>
```

For example:

```
https://www.osrsbox.com/osrsbox-db/items-json/1.json
```

The publicly available data is currently used by the osrsbox-tooltips project, which is currently in use by at least one website. So the `docs` folder needs to stay where it is, or added to another repo with another `docs` folder. AFAIK you cannot change the docs folder location within the repo.

This brings up another structural issue. I think that most of the content in the repo is probably not highly beneficial to provide in a package. I can see the use of the items API and tools (and monsters API and quests API when finished), but am unsure about packaging other parts of the repository. For example, the code to build the item database (`items-db-tools`) is only really used by me to build/rebuild the database, and is probably not useful to others - and the code is currently a complete mess! I think the same is true for the extraction scripts. But keeping the code publicly available on the repo is still good.

I think that most people would use the package for one reason:

1. Use the API coupled with JSON data to write programs involving the items database (or monsters/quests in the future)

I am not sure of the best practices when building a package... Can we have a folder in the repository with sub-folders/code that contain the package? For example, a folder named `osrsbox` which would be the package, with the `setup.py` file and the code for the package. Or should the package be an entire repo? Maybe there could be a new repo named `osrsbox` with just the APIs and tools and consolidated data (single JSON files) that make up the package? What are you ideas?

**Comment by nwalsh1995** [comment]
@osrsbox we can definitely be more selective on the modules that we are including into the package. I agree with your assessments on only having the API code without the DB generating code. 

As far as the discussion on creating a new repo or not, we can create a subfolder `osrsbox` and have that be the package. There is no requirement of having the whole repo be the package though that is what is commonly done. Personally, instead of creating a new repo I like the suggestion of just splitting up the user API from the data collection/extraction tools and putting it into new folders. However, if you want to create a repository that is also fine but might require marginally more maintenance.

**Comment by osrsbox** [comment]
Thanks for the feedback @nwalsh1995. I think the idea of creating a new `osrsbox` folder in the current repo (osrsbox-db) sounds like the best solution. To put my thoughts down, I see the following structure:

- `docs`
- `extraction_tools_cache`
- `extraction_tools_other`
- `extraction_tools_wiki`
- `items_build_db` (note a new name based on #22)
- `osrsbox` (the package)
    - `data` (similar content to docs folder, but only amalgamated JSON files e.g., `items_complete.json`)
    - `items_api` (note a new name based on #22)
    - `items_tools` (note a new name based on #22)
- `test`

I think including some tools in the package (as well as the API) is a good idea, especially if some more useful (for the end user) examples are added. In the future, the bestiary/monsters project will have a `monsters_build_db` in the root folder, and `monsters_api` and `monsters_tools` folder in the `osrsbox` folder.

To get started, I will finish #36 and #22 - this will tidy up the repo significantly and provide a good base structure for the package.

**Comment by nwalsh1995** [comment]
I am going to close out this PR since its old and we have decided which direction to take.

**Pull request closed without merging**
