### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by Little0smit**
Quick fix to a small typo in README file

### CODE REVIEW

**Comment by osrsbox** [comment]
Hey @Little0smit - thank you for the typo fix! I always appreciate any help.

**Comment by Little0smit** [comment]
No worries @osrsbox , hoping to use some of your data in one of my own programs so nice to be able to help somewhat.

**Comment by osrsbox** [comment]
@Little0smit - feel free to use the data, I am stoked when it is of use to other scapers! And happy to have help on the project. I just looked at your GitHub page and you projects... and wondering if you are the "One chunk at a time" ironman with the recent YouTube video series?? (I am guessing based on the project topics!)

On a side note, but might have relevance to you... I was recently looking at making a RuneLite plugin that "scans" in-game areas for ground items (default item spawn locations) and also NPCs. Then collecting the data, and mapping them using [Explv's map](https://github.com/Explv/Explv.github.io). The map has built-in "chunk" support (they call them "regions"), and it is open source. Haven't got around to the RuneLite plugin development yet... but thought the idea might be of interest to you. Could even do cool stuff like correlate quest NPCs to "chunks" - and probably many other similar ideas.

**Comment by Little0smit** [comment]
@osrsbox - Not the original video maker, but copied from the series. Am part of his discord and the project is being created as a global tool for anyone wanting to copy his idea. Must note i am fairly new to using github properly so also using this program as an excuse to try things out/learn it.

That idea certainly sounds really interesting, and would be greatly beneficial to mine as i feel the slowest part will be the collection of the data not the program itself, I will defiantly follow along if you have any progress with it. 

Many thanks again.

**Comment by osrsbox** [comment]
@Little0smit - super cool to get behind the idea/project. There is nothing like getting a good project to learn GitHub/git/programming better. I am in the same boat, and have learnt a lot from managing this project.

I will keep you in the loop with development of the RuneLite "worldscanner" plugin (just made up that name!). I have a little code written already - but still ironing out issues with the data collection. It seems a major limitation in OSRS is that there is lots of information... but not as much data in easily processed formats (e.g., JSON). Hopefully projects like yours help add to the data that is available! Good luck with the project, and will place a comment here when I get the RuneLite plugin working - this has given me some much needed motivation!

**Pull request merged**
