### PR TITLE
remove properties from ItemDefinition class and clean code

### PR DESCRIPTION
**Pull request by nwalsh1995**
A few things:

- The properties are no longer needed in the class since we aren't doing anything special around getting/setting
- We move all the properties to their normal names in the init
- We don't need the `load_from_file` since we can pass the dictionary into the constructor as kwargs.

I've added a few TODOs that we can pick up later. They are pretty minor currently.

### CODE REVIEW

**Comment by osrsbox** [comment]
@nwalsh1995 - I like this change, it is simple and elegant. There is one problem making this pull request: The `items_builder` code still uses the `items_api` getters and setters when rebuilding the item database after each weekly game update. However, it makes me wonder if the getters/setters should be somewhere else? For example, in the actual `items_builder` code - this was how it used to be structured, but I ended up changing item properties, then having to change the code in two places. Not too sure what the solution is... any feedback on what the best practices for this would be?

**Comment by nwalsh1995** [comment]
With this PR there are no 'getter / setters'. Everything is now being accessed directly, which in Python is perfectly okay since we can add properties later that maintain the same syntax. 

RE: changing the code in two places, I think you are talking about the `populate_from_scraper` method from `item_builder.py`? We can change this to call the `init` method in a similar way to what is shown in this PR by unpacking the dictionary. That way, if something new is added to the `init` the `**item_json` will still unpack everything. The only thing we would need to do is change the keys in the `item_json` dict to match the parameters in the `__init__`.

When you are dealing with referencing class attributes it becomes difficult not to couple the code directly with them and must change the code twice if the attribute name changes. Once the class becomes more 'permanent' this isn't much of a problem since the attributes aren't likely to change.

**Comment by osrsbox** [comment]
That makes perfect sense. FYI - I will accept 
and merge the PR after the next game update since I don't have time in the next day to update the `items_builder` code at the moment. Just don't want to break it before the immanent game update.

**Comment by osrsbox** [comment]
Wondering.... If we are changing the `item_definition.py` structure, maybe we should also update the `item_equipment.py` and `item_stats.py` files - as they have the same getter/setter for the properties. I also feel like these two separate modules/classes are not really needed - and should probably be merge together as non-equipable item are held by the `item_definition` and equipable items have the `item_definition`, `item_stats` and `item_equipment`. Doesn't really make sense to have the two classes that all equipable items have.

Anyway for the sake of this PR. It would make sense to just merge. Then update the following:

- Combine `item_stats` and `item_equipment`
- Update class properties as done in the PR

**Pull request merged**
